---
#System Settings
php_modules: [ 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip' ]

#MySQL Settings
mysql_root_password: "U~<b;3xq@E%H(Ckf"
mysql_db: "arctx-wp"
mysql_user: "arctx"
mysql_password: "N<w64dZ.pXa,Xbq@"

#HTTP Settings
http_host: "your_domain"
http_conf: "your_domain.conf"
http_port: "80"
